name: Spellcheck
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: read
jobs:
  Spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup Node.js 20
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: yarn
      - name: Run Spellcheck
        run: yarn spellcheck
